### ISSUE TITLE
TAGs with spaces

### ISSUE THREAD

**Issue by tschaturanga** [share-extras/site-tags-dashlet#1]
Dear Mr. Abson,

thank you for the site-tags-dashlet!

Users of our alfresco installation have taged their documents etc. with tags containing spaces, e.g. 'catalyst c3750'.  The site-tag-dashlet generates the following url for that tag:

http://xxx.yyy.de:8080/share/page/site/KOBIT/search?tag=catalyst%20c3750&a=false

The result set shows all document with 'catalyst' or 'c3750' in tags and content.
Enclosing the tag in the url with single quotes leads to a correct result set. So I changed the following line of getUriTemplate in file site-tags.js from

uri += '/search?tag=' + encodeURIComponent(tag.name) + '&amp;a=false';

to 

uri += '/search?tag=' + '\'' + encodeURIComponent(tag.name) + '\'' + '&amp;a=false';

If this is ok for you, please adopt this in the next dashlet version.

Best Regards

Manfred Lauer

**Comment by wabson** [comment]
Thank you for raising this. I have fixed this in the master branch and it is available as a release here - http://sharextras.org/artifacts/site-tags-dashlet-2.0.1.jar
